import{a as E,S as q,i as s}from"./assets/vendor-BgmC94F3.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const P="https://pixabay.com/api/",R="53020788-f0e72ace7309c782074e3a3d3",d=15;async function m(n,o){const r={key:R,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:d},{data:i}=await E.get(P,{params:r});return i}const h=document.querySelector(".gallery"),g=document.querySelector(".loader"),y=document.querySelector(".load-more"),B=new q(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function p(n){const o=n.map(({largeImageURL:r,webformatURL:i,tags:e,likes:t,views:l,comments:S,downloads:v})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${r}">
         <img class="gallery-img" src="${i}" alt="${e}"loading="lazy" />
        </a>
    
        <ul class="info">
          <li>Likes:${t}</li>
          <li>Views:${l}</li>
          <li>Comments:${S}</li>
          <li>Downloads:${v}</li>
        </ul>
      </li>`).join("");h.insertAdjacentHTML("beforeend",o),B.refresh()}function M(){h.innerHTML=""}function L(){g.classList.remove("hidden")}function w(){g.classList.add("hidden")}function $(){y.classList.remove("is-hidden")}function b(){y.classList.add("is-hidden")}const f=document.querySelector(".form"),O=f.elements["search-text"],x=document.querySelector(".load-more"),A=document.querySelector(".gallery");let u="",a=1,c=0;f.addEventListener("submit",C);x.addEventListener("click",H);async function C(n){n.preventDefault();const o=O.value.trim();if(!o){s.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}u=o,a=1,c=0,M(),b(),L();try{const r=await m(u,a),{hits:i,totalHits:e}=r;if(c=e,!i.length){s.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(i),a*d<c?$():s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{s.error({title:"Error",message:"Something went wrong while fetching images.",position:"topRight"})}finally{w(),f.reset()}}async function H(){a+=1,L();try{const n=await m(u,a),{hits:o}=n;p(o);const r=A.firstElementChild;if(r){const{height:i}=r.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}a*d>=c&&(b(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{s.error({title:"Error",message:"Unable to load more images.",position:"topRight"})}finally{w()}}
//# sourceMappingURL=index.js.map
